docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - usage.md
    - Checks:
        - "Diagnostic Checks": diagnostics.md
        - "File Validation Checks": file-validation.md
    - Reference:
        - Architecture: architecture.md
        - "Custom Checks": custom-checks.md
        - "Custom Reporters": custom-reporters.md
site_name: laminas-diagnostics
site_description: 'A set of components for performing diagnostic tests in PHP applications.'
repo_url: 'https://github.com/laminas/laminas-diagnostics'
